server:
  port: 8091
tomcat:
  max-threads: 10

spring:
  application:
    name: service-order
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://sh-cynosdbmysql-grp-r8gneeuy.sql.tencentcdb.com:27290/mall_tiny?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&autoReconnect=true&useSSL=false
    username: root
    password: czs7xtu4123-
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
          dialect: org.hibernate.dialect.MySQL5InnoDBDialect